### ISSUE TITLE
Filenames are changed in conversion

### ISSUE THREAD

**Issue by peterennis** [simplesvg/tools#3]
My_File_Name.svg becomes my-file-name.svg

Is there an option to not change file names?

![capture317](https://user-images.githubusercontent.com/140737/40582496-361774b6-612d-11e8-835d-299e0540bd25.png)

**Comment by cyberalien** [comment]
Sure. I assume you are using ImportDir module, then in module options specify keywordCallback option like this:

```
ImportDir(dir, {
    keywordCallback: function(key, file) {
        let result = file.split('/');
        return result.pop();
    }
})
```

**Comment by peterennis** [comment]
`modules.js` shows this: `ImportDir: require('./import/dir'),`

The only other reference to `ImportDir` is in the `parse.js` example:

```
// Do stuff
tools.ImportDir(sourceDir).then(result => {
    collection = result;
    console.log('Found ' + collection.length() + ' icons.');
```

Sorry, I don't understand how to use the example you provided.

**Comment by cyberalien** [comment]
What code are you using?

**Comment by peterennis** [comment]
I am using a modification of this: https://github.com/simplesvg/tools/blob/master/sample/parse.js and passing in the absolute path to the files.

**Comment by peterennis** [comment]
@cyberalien, That worked. Thanks!
